name: notustohtml
description: Convert the Notus document format to an HTML representation.
version: 0.0.9
homepage: https://github.com/JacobWrenn/notustohtml

environment:
  sdk: ">=2.8.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  notus: ^0.1.5
  quill_delta: 1.0.2
  html: 0.15.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
